name: face_recognition_app
description: A Face Recognition Based Attendance Capturing App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  intl: ^0.17.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  hexcolor: ^2.0.3
  fluttertoast: ^8.0.6
  dio: ^4.0.0
  flutter_speed_dial: ^3.0.5
  tflite_flutter: ^0.8.0
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0
  firebase_ml_vision: ^0.12.0+1
  image: ^3.0.2
  firebase_core: ^1.1.1
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3
  flutter_downloader: ^1.6.1
  permission_handler: ^8.1.1
  syncfusion_flutter_xlsio: ^19.1.69-beta
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/logo.jpg"
  adaptive_icon_background: "dev_assets/logo.jpg"
  adaptive_icon_foreground: "dev_assets/logo.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/mobilefacenet.tflite
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-Light.ttf
        - asset: assets/fonts/Hind-Regular.ttf
        - asset: assets/fonts/Hind-Medium.ttf
        - asset: assets/fonts/Hind-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Hind-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
